import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const car = searchParams.get('car');

  if (!car) {
    return new NextResponse('Missing car parameter', { status: 400 });
  }

  // Map of car identifiers to the exact artifact filenames generated by the AI
  const artifactMapping: Record<string, string> = {
    'toyota_avanza': 'toyota_avanza_1775807002684.png',
    'honda_brio': 'honda_brio_1775807018260.png',
    'suzuki_ertiga': 'suzuki_ertiga_1775807036319.png',
    'toyota_innova_zenix': 'toyota_innova_zenix_1775807055535.png',
    'honda_crv': 'honda_crv_1775807079262.png',
    'mitsubishi_pajero_sport': 'mitsubishi_pajero_sport_1775807107602.png',
    'toyota_alphard': 'toyota_alphard_1775807127591.png',
    'lexus_lm': 'lexus_lm_1775807146468.png',
    'mercedes_s_class': 'mercedes_s_class_1775807162769.png',
    'bmw_7_series': 'bmw_7_series_1775807177351.png'
  };

  const filename = artifactMapping[car];
  if (!filename) {
    return new NextResponse('Car not found', { status: 404 });
  }

  const baseDir = 'C:\\Users\\LENOVO\\.gemini\\antigravity\\brain\\0056983c-c258-4bfb-8c10-179ed754698c';
  const filePath = path.join(baseDir, filename);

  try {
    const fileBuffer = fs.readFileSync(filePath);
    return new NextResponse(fileBuffer, {
      headers: {
        'Content-Type': 'image/png',
        'Cache-Control': 'public, max-age=31536000, immutable',
      },
    });
  } catch (err) {
    console.error('Error reading artifact image:', err);
    return new NextResponse('Image file not found on disk', { status: 404 });
  }
}
